In [53]:
import pandas as pd

c19cases = pd.read_csv('time_series_covid19_confirmed_US.csv')

c19cases.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,3/7/21,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21
0,84001001,US,USA,840,1001.0,Autauga,Alabama,US,32.539527,-86.644082,...,6347,6364,6371,6400,6409,6409,6416,6426,6471,6474
1,84001003,US,USA,840,1003.0,Baldwin,Alabama,US,30.727750,-87.722071,...,19935,19942,19962,20012,20044,20072,20091,20103,20210,20227
2,84001005,US,USA,840,1005.0,Barbour,Alabama,US,31.868263,-85.387129,...,2139,2143,2147,2161,2171,2175,2181,2184,2195,2198
3,84001007,US,USA,840,1007.0,Bibb,Alabama,US,32.996421,-87.125115,...,2465,2464,2466,2469,2474,2475,2479,2481,2499,2508
4,84001009,US,USA,840,1009.0,Blount,Alabama,US,33.982109,-86.567906,...,6256,6256,6255,6260,6274,6282,6288,6291,6353,6361

In [49]:
#orig county list DO NOT RUN

c19df = c19cases[(c19cases['Province_State'] == 'New York') & (c19cases['Admin2'] == 'Onondaga')]
                 
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Illinois') & (c19cases['Admin2'] == 'Lake')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Virginia') & (c19cases['Admin2'] == 'Manassas Park')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Missouri') & (c19cases['Admin2'] == 'Clay')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Virginia') & (c19cases['Admin2'] == 'Virginia Beach')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Florida') & (c19cases['Admin2'] == 'Pinellas')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Pennsylvania') & (c19cases['Admin2'] == 'Lancaster')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Texas') & (c19cases['Admin2'] == 'Galveston')])
c19df = c19df.append(c19cases[(c19cases['Province_State'] == 'Texas') & (c19cases['Admin2'] == 'Harris')])

        
# c19df

In [54]:
# new dataframe of selected counties
counties = pd.read_csv('county_info_new.csv', index_col = [0]) #note csv file name
counties.rename({'counties': 'county'}, axis='columns', inplace = True)
counties

,county,state,populations,ed_rate,tier,lat/lon,FIPS County Code
0,New York,New York,69468,0.613,2,"40.7741618671, -73.9697971209",36061
1,San Francisco,California,17179,0.581,2,"37.7597150131, -122.693975573",6075
2,Hudson,New Jersey,13732,0.423,1,"40.7309049975, -74.0759554422",34017
3,Suffolk,Massachusetts,12417,0.461,2,"42.3486893925, -70.9856096697",36103
4,Philadelphia,Pennsylvania,11379,0.297,1,"40.0076360466, -75.1339446794",42101
5,District of Columbia,District of Columbia,9857,0.585,2,"38.9047737146, -77.0163026702",11001
6,Alexandria,Virginia,9314,0.631,3,"38.8184535854, -77.0862060584",51510
7,Baltimore,Maryland,7672,0.394,1,"39.443072852, -76.6163229502",24005
8,Cook,Illinois,5495,0.388,1,"41.8954290221, -87.6461407931",17031
9,St. Louis,Missouri,5157,0.436,1,"38.6406885662, -90.4433975603",29189
10,Milwaukee,Wisconsin,3926,0.310,1,"43.0154568883, -87.5805486607",55079
11,Denver,Colorado,3923,0.494,2,"39.7621646287, -104.875801423",8031
12,Orange,California,3808,0.406,1,"33.6769134328, -117.776142822",6059
13,Pinellas,Florida,3348,0.317,1,"27.9026762041, -82.7395539464",12103
14,Ramsey,Minnesota,3342,0.423,1,"45.0170541432, -93.099606274",27123
15,Wayne,Michigan,2974,0.239,1,"42.2847454761, -83.2611328686",26163
16,Cuyahoga,Ohio,2800,0.325,1,"41.6350590585, -81.7001959208",39035
17,Dallas,Texas,2718,0.315,1,"32.7666300195, -96.7778770663",48113
18,DeKalb,Georgia,2586,0.442,2,"33.7715468713, -84.226432416",13089
19,Salt Lake,Utah,1387,0.356,1,"40.6673139262, -111.923601307",49035
20,Marion,Indiana,2279,0.309,1,"39.7817096805, -86.1384716709",18097
21,Jefferson,Kentucky,1948,0.334,1,"38.1871910002, -85.6591577058",21111
22,Johnson,Kansas,1149,0.560,2,"38.8837685125, -94.8222610425",20091
23,King,Washington,912,0.525,2,"47.4909231926, -121.83595173",53045

In [55]:
# CLEANING OF ORIG COUNTY CSV FILE, DO NOT RUN
states = []
counties_lst = []

for index, county in counties.iterrows():
    states.append(county['county'][-2:])
    counties_lst.append(county['county'][0:-3])
    
counties['state'] = states
counties['county'] = counties_lst


counties = counties[['county', 'state', 'populations', 'ed_rate', 'tier', 'lat/lon']]

#counties

In [8]:
# Collecting COVID-19 data according to the counties listed in county_info_new.csv

c19df = pd.DataFrame()

for index, county in counties.iterrows():
    c19df = c19df.append(c19cases[(c19cases['Province_State'] == str(county['state'])) & 
                          (c19cases['Admin2'] == str(county['county']))])
    
    

c19df

#c19df.to_csv('covid_cases.csv')

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,3/7/21,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21
1930,84036061,US,USA,840,36061.0,New York,New York,US,40.767273,-73.971526,...,107585,108031,108580,109015,109618,110289,110727,111336,111991,112440
233,84006075,US,USA,840,6075.0,San Francisco,California,US,37.752151,-122.438567,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
1850,84034017,US,USA,840,34017.0,Hudson,New Jersey,US,40.737662,-74.075157,...,71406,71635,71969,72300,72644,73009,73292,73595,73816,74064
1277,84025025,US,USA,840,25025.0,Suffolk,Massachusetts,US,42.327951,-71.078504,...,79597,79724,79835,80026,80231,80450,80655,80886,81002,81092
2380,84042101,US,USA,840,42101.0,Philadelphia,Pennsylvania,US,40.003385,-75.137927,...,119874,120539,120966,121242,121583,121881,121881,121881,122598,122971
337,84011001,US,USA,840,11001.0,District of Columbia,District of Columbia,US,38.904178,-77.016560,...,41419,41579,41910,42006,42128,42282,42432,42511,42623,42730
3010,84051510,US,USA,840,51510.0,Alexandria,Virginia,US,38.814003,-77.081831,...,10445,10456,10468,10490,10504,10529,10548,10570,10592,10617
1239,84024005,US,USA,840,24005.0,Baltimore,Maryland,US,39.457847,-76.629120,...,51730,51862,51966,52096,52271,52450,52606,52740,52828,52936
640,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,...,478884,479361,479913,480487,481101,481787,482424,482973,483282,484146
1642,84029189,US,USA,840,29189.0,St. Louis,Missouri,US,38.637700,-90.445837,...,89373,89452,89599,89767,89929,90113,90287,90398,90479,90641
3281,84055079,US,USA,840,55079.0,Milwaukee,Wisconsin,US,43.004861,-87.967332,...,107719,107745,107786,107920,107993,108091,108144,108218,108272,108378
271,84008031,US,USA,840,8031.0,Denver,Colorado,US,39.760183,-104.872569,...,60614,60715,60810,61117,61246,61442,61583,61788,61859,61880
224,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,...,262674,262849,262995,263111,263279,263471,263653,263823,263994,264033
392,84012103,US,USA,840,12103.0,Pinellas,Florida,US,27.931303,-82.722397,...,67844,67961,68085,68258,68494,68744,68912,69063,69192,69334
1429,84027123,US,USA,840,27123.0,Ramsey,Minnesota,US,45.016253,-93.098723,...,43388,43406,43556,43616,43660,43724,43796,43846,43890,43924
1365,84026163,US,USA,840,26163.0,Wayne,Michigan,US,42.280984,-83.281255,...,103560,104024,104229,104708,105041,105591,105874,105874,106587,106994
2139,84039035,US,USA,840,39035.0,Cuyahoga,Ohio,US,41.424119,-81.659183,...,96933,97121,97369,97639,97792,97975,98207,98295,98473,98710
2754,84048113,US,USA,840,48113.0,Dallas,Texas,US,32.766706,-96.777961,...,284010,284010,284935,285332,285683,286084,286351,286351,286925,287236
451,84013089,US,USA,840,13089.0,DeKalb,Georgia,US,33.769440,-84.223960,...,58143,58234,58357,58493,58629,58752,58851,58891,59001,59194
2974,84049035,US,USA,840,49035.0,Salt Lake,Utah,US,40.666165,-111.921601,...,139976,140070,140250,140455,140680,140867,141033,141197,141289,141444
777,84018097,US,USA,840,18097.0,Marion,Indiana,US,39.781636,-86.138263,...,91354,91411,91481,91558,91657,91757,91841,91934,91973,92031
1086,84021111,US,USA,840,21111.0,Jefferson,Kentucky,US,38.186647,-85.659310,...,73919,73982,74140,74284,74456,74629,74731,74804,74891,75027
969,84020091,US,USA,840,20091.0,Johnson,Kansas,US,38.885482,-94.822509,...,54730,54889,54889,55084,55084,55185,55185,55185,55287,55287
3159,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655

In [56]:
#resetting index for ease of adding columns
c19newdf = pd.DataFrame(c19df)

c19newdf.reset_index()

,index,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,...,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21,county
0,1930,84036061,US,USA,840,36061.0,New York,New York,US,40.767273,...,108031,108580,109015,109618,110289,110727,111336,111991,112440,New York County NY
1,233,84006075,US,USA,840,6075.0,San Francisco,California,US,37.752151,...,34594,34634,34654,34688,34722,34758,34784,34810,34820,County of San Francisco CA
2,1850,84034017,US,USA,840,34017.0,Hudson,New Jersey,US,40.737662,...,71635,71969,72300,72644,73009,73292,73595,73816,74064,Hudson County NJ
3,1277,84025025,US,USA,840,25025.0,Suffolk,Massachusetts,US,42.327951,...,79724,79835,80026,80231,80450,80655,80886,81002,81092,Suffolk County MA
4,2380,84042101,US,USA,840,42101.0,Philadelphia,Pennsylvania,US,40.003385,...,120539,120966,121242,121583,121881,121881,121881,122598,122971,Philadelphia County PA
5,337,84011001,US,USA,840,11001.0,District of Columbia,District of Columbia,US,38.904178,...,41579,41910,42006,42128,42282,42432,42511,42623,42730,Washington DC
6,3010,84051510,US,USA,840,51510.0,Alexandria,Virginia,US,38.814003,...,10456,10468,10490,10504,10529,10548,10570,10592,10617,Alexandria VA
7,1239,84024005,US,USA,840,24005.0,Baltimore,Maryland,US,39.457847,...,51862,51966,52096,52271,52450,52606,52740,52828,52936,Baltimore MD
8,640,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,...,479361,479913,480487,481101,481787,482424,482973,483282,484146,Cook County IL
9,1642,84029189,US,USA,840,29189.0,St. Louis,Missouri,US,38.637700,...,89452,89599,89767,89929,90113,90287,90398,90479,90641,St. Louis County MO
10,3281,84055079,US,USA,840,55079.0,Milwaukee,Wisconsin,US,43.004861,...,107745,107786,107920,107993,108091,108144,108218,108272,108378,Milwaukee County WI
11,271,84008031,US,USA,840,8031.0,Denver,Colorado,US,39.760183,...,60715,60810,61117,61246,61442,61583,61788,61859,61880,Denver County CO
12,224,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,...,262849,262995,263111,263279,263471,263653,263823,263994,264033,Orange County CA
13,392,84012103,US,USA,840,12103.0,Pinellas,Florida,US,27.931303,...,67961,68085,68258,68494,68744,68912,69063,69192,69334,Pinellas County FL
14,1429,84027123,US,USA,840,27123.0,Ramsey,Minnesota,US,45.016253,...,43406,43556,43616,43660,43724,43796,43846,43890,43924,Ramsey County MN
15,1365,84026163,US,USA,840,26163.0,Wayne,Michigan,US,42.280984,...,104024,104229,104708,105041,105591,105874,105874,106587,106994,"Wayne County, MI"
16,2139,84039035,US,USA,840,39035.0,Cuyahoga,Ohio,US,41.424119,...,97121,97369,97639,97792,97975,98207,98295,98473,98710,Cuyahoga County OH
17,2754,84048113,US,USA,840,48113.0,Dallas,Texas,US,32.766706,...,284010,284935,285332,285683,286084,286351,286351,286925,287236,Dallas County TX
18,451,84013089,US,USA,840,13089.0,DeKalb,Georgia,US,33.769440,...,58234,58357,58493,58629,58752,58851,58891,59001,59194,DeKalb County GA
19,2974,84049035,US,USA,840,49035.0,Salt Lake,Utah,US,40.666165,...,140070,140250,140455,140680,140867,141033,141197,141289,141444,Salt Lake County UT
20,777,84018097,US,USA,840,18097.0,Marion,Indiana,US,39.781636,...,91411,91481,91558,91657,91757,91841,91934,91973,92031,Marion County IN
21,1086,84021111,US,USA,840,21111.0,Jefferson,Kentucky,US,38.186647,...,73982,74140,74284,74456,74629,74731,74804,74891,75027,Jefferson County KY
22,969,84020091,US,USA,840,20091.0,Johnson,Kansas,US,38.885482,...,54889,54889,55084,55084,55185,55185,55185,55287,55287,Johnson County KS
23,3159,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,...,85282,85417,85596,85824,86002,86234,86234,86540,86655,King County WA

In [57]:
# Adding different naming conventions to dataframe to match with tweet collection dataframe. 
# NOTE THE ALTERATIONS IN LIST, NAMELY TEST TX LOC. THIS NEW LIST IS IN LINE WITH county_info_new.csv

tweet_locs = pd.Series([
'New York County NY',
 'County of San Francisco CA',
 'Hudson County NJ',
 'Suffolk County MA',
 'Philadelphia County PA',
 'Washington DC',
 'Alexandria VA',
 'Baltimore MD',
 'Cook County IL',
 'St. Louis County MO',
 'Milwaukee County WI',
 'Denver County CO',
 'Orange County CA',
 'Pinellas County FL',
 'Ramsey County MN',
 'Wayne County, MI',
 'Cuyahoga County OH',
 'Dallas County TX',
 'DeKalb County GA',
 'Salt Lake County UT',
 'Marion County IN',
 'Jefferson County KY',
 'Johnson County KS',
 'King County WA'])

c19newdf['county'] = tweet_locs.values

# we can add the education data + any other data contained in the county_info_new.csv at this point

In [19]:
c19newdf # cols added to end of dataframe, we can change the order if we want

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,...,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21,county
1930,84036061,US,USA,840,36061.0,New York,New York,US,40.767273,-73.971526,...,108031,108580,109015,109618,110289,110727,111336,111991,112440,New York County NY
233,84006075,US,USA,840,6075.0,San Francisco,California,US,37.752151,-122.438567,...,34594,34634,34654,34688,34722,34758,34784,34810,34820,County of San Francisco CA
1850,84034017,US,USA,840,34017.0,Hudson,New Jersey,US,40.737662,-74.075157,...,71635,71969,72300,72644,73009,73292,73595,73816,74064,Hudson County NJ
1277,84025025,US,USA,840,25025.0,Suffolk,Massachusetts,US,42.327951,-71.078504,...,79724,79835,80026,80231,80450,80655,80886,81002,81092,Suffolk County MA
2380,84042101,US,USA,840,42101.0,Philadelphia,Pennsylvania,US,40.003385,-75.137927,...,120539,120966,121242,121583,121881,121881,121881,122598,122971,Philadelphia County PA
337,84011001,US,USA,840,11001.0,District of Columbia,District of Columbia,US,38.904178,-77.016560,...,41579,41910,42006,42128,42282,42432,42511,42623,42730,Washington DC
3010,84051510,US,USA,840,51510.0,Alexandria,Virginia,US,38.814003,-77.081831,...,10456,10468,10490,10504,10529,10548,10570,10592,10617,Alexandria VA
1239,84024005,US,USA,840,24005.0,Baltimore,Maryland,US,39.457847,-76.629120,...,51862,51966,52096,52271,52450,52606,52740,52828,52936,Baltimore MD
640,84017031,US,USA,840,17031.0,Cook,Illinois,US,41.841448,-87.816588,...,479361,479913,480487,481101,481787,482424,482973,483282,484146,Cook County IL
1642,84029189,US,USA,840,29189.0,St. Louis,Missouri,US,38.637700,-90.445837,...,89452,89599,89767,89929,90113,90287,90398,90479,90641,St. Louis County MO
3281,84055079,US,USA,840,55079.0,Milwaukee,Wisconsin,US,43.004861,-87.967332,...,107745,107786,107920,107993,108091,108144,108218,108272,108378,Milwaukee County WI
271,84008031,US,USA,840,8031.0,Denver,Colorado,US,39.760183,-104.872569,...,60715,60810,61117,61246,61442,61583,61788,61859,61880,Denver County CO
224,84006059,US,USA,840,6059.0,Orange,California,US,33.701475,-117.764600,...,262849,262995,263111,263279,263471,263653,263823,263994,264033,Orange County CA
392,84012103,US,USA,840,12103.0,Pinellas,Florida,US,27.931303,-82.722397,...,67961,68085,68258,68494,68744,68912,69063,69192,69334,Pinellas County FL
1429,84027123,US,USA,840,27123.0,Ramsey,Minnesota,US,45.016253,-93.098723,...,43406,43556,43616,43660,43724,43796,43846,43890,43924,Ramsey County MN
1365,84026163,US,USA,840,26163.0,Wayne,Michigan,US,42.280984,-83.281255,...,104024,104229,104708,105041,105591,105874,105874,106587,106994,"Wayne County, MI"
2139,84039035,US,USA,840,39035.0,Cuyahoga,Ohio,US,41.424119,-81.659183,...,97121,97369,97639,97792,97975,98207,98295,98473,98710,Cuyahoga County OH
2754,84048113,US,USA,840,48113.0,Dallas,Texas,US,32.766706,-96.777961,...,284010,284935,285332,285683,286084,286351,286351,286925,287236,Dallas County TX
451,84013089,US,USA,840,13089.0,DeKalb,Georgia,US,33.769440,-84.223960,...,58234,58357,58493,58629,58752,58851,58891,59001,59194,DeKalb County GA
2974,84049035,US,USA,840,49035.0,Salt Lake,Utah,US,40.666165,-111.921601,...,140070,140250,140455,140680,140867,141033,141197,141289,141444,Salt Lake County UT
777,84018097,US,USA,840,18097.0,Marion,Indiana,US,39.781636,-86.138263,...,91411,91481,91558,91657,91757,91841,91934,91973,92031,Marion County IN
1086,84021111,US,USA,840,21111.0,Jefferson,Kentucky,US,38.186647,-85.659310,...,73982,74140,74284,74456,74629,74731,74804,74891,75027,Jefferson County KY
969,84020091,US,USA,840,20091.0,Johnson,Kansas,US,38.885482,-94.822509,...,54889,54889,55084,55084,55185,55185,55185,55287,55287,Johnson County KS
3159,84053033,US,USA,840,53033.0,King,Washington,US,47.491379,-121.834613,...,85282,85417,85596,85824,86002,86234,86234,86540,86655,King County WA

# Joining dataframes

In [58]:
tweets = pd.read_csv('cleaned_tweets_finalquery.csv', index_col = [0])

In [59]:
tweets_and_c19 = tweets.merge(c19newdf, on='county')
tweets_and_c19

,county,original_tweet,tweets_list,tweet_str,tweet_slice,tweet_text,UID,iso2,iso3,code3,...,3/7/21,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21
0,County of San Francisco CA,"['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...",bly disabled enough to get the vaccine (or may...,'if you live in supportive housing you are pro...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
1,County of San Francisco CA,['@robini71 @technolass I have mask fatigue an...,"['If you live in supportive housing, you are p...",['@robini71 @technolass I have mask fatigue an...,ill after all this time hatred and anxiety tra...,'robini technolass i have mask fatigue and sti...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
2,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/qWAQiZsJWX'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
3,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/xHjDwTVEeg'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
4,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/2gYfKCKW3k'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,King County WA,['I never say anything to my cousin anymore bc...,['I never say anything to my cousin anymore bc...,['I never say anything to my cousin anymore bc...,is the only place she hasnâ€™t blocked me and I ...,'i never say anything to my cousin anymore bc ...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
268,King County WA,['@offgridteacher Iâ€™ve eaten indoors but the m...,['I never say anything to my cousin anymore bc...,['@offgridteacher Iâ€™ve eaten indoors but the m...,requirements are pretty strict (masks to enter...,'offgridteacher ive eaten indoors but the mask...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
269,King County WA,"[""@RantsByDesign I'm in mask-free TX, where we...",['I never say anything to my cousin anymore bc...,"[""@RantsByDesign I'm in mask-free TX, where we...",ll have 5k new cases/day.\n\nQuite ok with me ...,rantsbydesign i'm in mask-free tx where we sti...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
270,King County WA,['@ElwynLouis @sounderatheart I still believe ...,['I never say anything to my cousin anymore bc...,['@ElwynLouis @sounderatheart I still believe ...,hould be masked until absolutely everyone is c...,'elwynlouis sounderatheart i still believe we ...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
271,King County WA,"[""Fox News rouses mask-free Texans at '100% ca...",['I never say anything to my cousin anymore bc...,"[""Fox News rouses mask-free Texans at '100% ca...",ty' diner: 'Think for yourself like Lying Conm...,fox news rouses mask-free texans at ' capacity...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655

In [22]:
#trying to parse for duplicates, doesn't seem to be working
tweets_and_c19.drop_duplicates('original_tweet', inplace = True)

In [60]:
dates = '1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,2/1/20,2/2/20,2/3/20,2/4/20,2/5/20,2/6/20,2/7/20,2/8/20,2/9/20,2/10/20,2/11/20,2/12/20,2/13/20,2/14/20,2/15/20,2/16/20,2/17/20,2/18/20,2/19/20,2/20/20,2/21/20,2/22/20,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20,4/24/20,4/25/20,4/26/20,4/27/20,4/28/20,4/29/20,4/30/20,5/1/20,5/2/20,5/3/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,5/10/20,5/11/20,5/12/20,5/13/20,5/14/20,5/15/20,5/16/20,5/17/20,5/18/20,5/19/20,5/20/20,5/21/20,5/22/20,5/23/20,5/24/20,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20,6/4/20,6/5/20,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20,6/27/20,6/28/20,6/29/20,6/30/20,7/1/20,7/2/20,7/3/20,7/4/20,7/5/20,7/6/20,7/7/20,7/8/20,7/9/20,7/10/20,7/11/20,7/12/20,7/13/20,7/14/20,7/15/20,7/16/20,7/17/20,7/18/20,7/19/20,7/20/20,7/21/20,7/22/20,7/23/20,7/24/20,7/25/20,7/26/20,7/27/20,7/28/20,7/29/20,7/30/20,7/31/20,8/1/20,8/2/20,8/3/20,8/4/20,8/5/20,8/6/20,8/7/20,8/8/20,8/9/20,8/10/20,8/11/20,8/12/20,8/13/20,8/14/20,8/15/20,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20,8/28/20,8/29/20,8/30/20,8/31/20,9/1/20,9/2/20,9/3/20,9/4/20,9/5/20,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,9/15/20,9/16/20,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20,9/26/20,9/27/20,9/28/20,9/29/20,9/30/20,10/1/20,10/2/20,10/3/20,10/4/20,10/5/20,10/6/20,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20,10/12/20,10/13/20,10/14/20,10/15/20,10/16/20,10/17/20,10/18/20,10/19/20,10/20/20,10/21/20,10/22/20,10/23/20,10/24/20,10/25/20,10/26/20,10/27/20,10/28/20,10/29/20,10/30/20,10/31/20,11/1/20,11/2/20,11/3/20,11/4/20,11/5/20,11/6/20,11/7/20,11/8/20,11/9/20,11/10/20,11/11/20,11/12/20,11/13/20,11/14/20,11/15/20,11/16/20,11/17/20,11/18/20,11/19/20,11/20/20,11/21/20,11/22/20,11/23/20,11/24/20,11/25/20,11/26/20,11/27/20,11/28/20,11/29/20,11/30/20,12/1/20,12/2/20,12/3/20,12/4/20,12/5/20,12/6/20,12/7/20,12/8/20,12/9/20,12/10/20,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20,12/21/20,12/22/20,12/23/20,12/24/20,12/25/20,12/26/20,12/27/20,12/28/20,12/29/20,12/30/20,12/31/20,1/1/21,1/2/21,1/3/21,1/4/21,1/5/21,1/6/21,1/7/21,1/8/21,1/9/21,1/10/21,1/11/21,1/12/21,1/13/21,1/14/21,1/15/21,1/16/21,1/17/21,1/18/21,1/19/21,1/20/21,1/21/21,1/22/21,1/23/21,1/24/21,1/25/21,1/26/21,1/27/21,1/28/21,1/29/21,1/30/21,1/31/21,2/1/21,2/2/21,2/3/21,2/4/21,2/5/21,2/6/21,2/7/21,2/8/21,2/9/21,2/10/21,2/11/21,2/12/21,2/13/21,2/14/21,2/15/21,2/16/21,2/17/21,2/18/21,2/19/21,2/20/21,2/21/21,2/22/21,2/23/21,2/24/21,2/25/21,2/26/21,2/27/21,2/28/21,3/1/21,3/2/21,3/3/21,3/4/21,3/5/21,3/6/21,3/7/21,3/8/21,3/9/21'
    
dates = dates.split(",")

dates

['1/22/20',
 '1/23/20',
 '1/24/20',
 '1/25/20',
 '1/26/20',
 '1/27/20',
 '1/28/20',
 '1/29/20',
 '1/30/20',
 '1/31/20',
 '2/1/20',
 '2/2/20',
 '2/3/20',
 '2/4/20',
 '2/5/20',
 '2/6/20',
 '2/7/20',
 '2/8/20',
 '2/9/20',
 '2/10/20',
 '2/11/20',
 '2/12/20',
 '2/13/20',
 '2/14/20',
 '2/15/20',
 '2/16/20',
 '2/17/20',
 '2/18/20',
 '2/19/20',
 '2/20/20',
 '2/21/20',
 '2/22/20',
 '2/23/20',
 '2/24/20',
 '2/25/20',
 '2/26/20',
 '2/27/20',
 '2/28/20',
 '2/29/20',
 '3/1/20',
 '3/2/20',
 '3/3/20',
 '3/4/20',
 '3/5/20',
 '3/6/20',
 '3/7/20',
 '3/8/20',
 '3/9/20',
 '3/10/20',
 '3/11/20',
 '3/12/20',
 '3/13/20',
 '3/14/20',
 '3/15/20',
 '3/16/20',
 '3/17/20',
 '3/18/20',
 '3/19/20',
 '3/20/20',
 '3/21/20',
 '3/22/20',
 '3/23/20',
 '3/24/20',
 '3/25/20',
 '3/26/20',
 '3/27/20',
 '3/28/20',
 '3/29/20',
 '3/30/20',
 '3/31/20',
 '4/1/20',
 '4/2/20',
 '4/3/20',
 '4/4/20',
 '4/5/20',
 '4/6/20',
 '4/7/20',
 '4/8/20',
 '4/9/20',
 '4/10/20',
 '4/11/20',
 '4/12/20',
 '4/13/20',
 '4/14/20',
 '4/15/20',
 '4/16/20',
 '4/17/20',
 '4/18/20',
 '4/19/20',
 '4/20/20',
 '4/21/20',
 '4/22/20',
 '4/23/20',
 '4/24/20',
 '4/25/20',
 '4/26/20',
 '4/27/20',
 '4/28/20',
 '4/29/20',
 '4/30/20',
 '5/1/20',
 '5/2/20',
 '5/3/20',
 '5/4/20',
 '5/5/20',
 '5/6/20',
 '5/7/20',
 '5/8/20',
 '5/9/20',
 '5/10/20',
 '5/11/20',
 '5/12/20',
 '5/13/20',
 '5/14/20',
 '5/15/20',
 '5/16/20',
 '5/17/20',
 '5/18/20',
 '5/19/20',
 '5/20/20',
 '5/21/20',
 '5/22/20',
 '5/23/20',
 '5/24/20',
 '5/25/20',
 '5/26/20',
 '5/27/20',
 '5/28/20',
 '5/29/20',
 '5/30/20',
 '5/31/20',
 '6/1/20',
 '6/2/20',
 '6/3/20',
 '6/4/20',
 '6/5/20',
 '6/6/20',
 '6/7/20',
 '6/8/20',
 '6/9/20',
 '6/10/20',
 '6/11/20',
 '6/12/20',
 '6/13/20',
 '6/14/20',
 '6/15/20',
 '6/16/20',
 '6/17/20',
 '6/18/20',
 '6/19/20',
 '6/20/20',
 '6/21/20',
 '6/22/20',
 '6/23/20',
 '6/24/20',
 '6/25/20',
 '6/26/20',
 '6/27/20',
 '6/28/20',
 '6/29/20',
 '6/30/20',
 '7/1/20',
 '7/2/20',
 '7/3/20',
 '7/4/20',
 '7/5/20',
 '7/6/20',
 '7/7/20',
 '7/8/20',
 '7/9/20',
 '7/10/20',
 '7/11/20',
 '7/12/20',
 '7/13/20',
 '7/14/20',
 '7/15/20',
 '7/16/20',
 '7/17/20',
 '7/18/20',
 '7/19/20',
 '7/20/20',
 '7/21/20',
 '7/22/20',
 '7/23/20',
 '7/24/20',
 '7/25/20',
 '7/26/20',
 '7/27/20',
 '7/28/20',
 '7/29/20',
 '7/30/20',
 '7/31/20',
 '8/1/20',
 '8/2/20',
 '8/3/20',
 '8/4/20',
 '8/5/20',
 '8/6/20',
 '8/7/20',
 '8/8/20',
 '8/9/20',
 '8/10/20',
 '8/11/20',
 '8/12/20',
 '8/13/20',
 '8/14/20',
 '8/15/20',
 '8/16/20',
 '8/17/20',
 '8/18/20',
 '8/19/20',
 '8/20/20',
 '8/21/20',
 '8/22/20',
 '8/23/20',
 '8/24/20',
 '8/25/20',
 '8/26/20',
 '8/27/20',
 '8/28/20',
 '8/29/20',
 '8/30/20',
 '8/31/20',
 '9/1/20',
 '9/2/20',
 '9/3/20',
 '9/4/20',
 '9/5/20',
 '9/6/20',
 '9/7/20',
 '9/8/20',
 '9/9/20',
 '9/10/20',
 '9/11/20',
 '9/12/20',
 '9/13/20',
 '9/14/20',
 '9/15/20',
 '9/16/20',
 '9/17/20',
 '9/18/20',
 '9/19/20',
 '9/20/20',
 '9/21/20',
 '9/22/20',
 '9/23/20',
 '9/24/20',
 '9/25/20',
 '9/26/20',
 '9/27/20',
 '9/28/20',
 '9/29/20',
 '9/30/20',
 '10/1/20',
 '10/2/20',
 '10/3/20',
 '10/4/20',
 '10/5/20',
 '10/6/20',
 '10/7/20',
 '10/8/20',
 '10/9/20',
 '10/10/20',
 '10/11/20',
 '10/12/20',
 '10/13/20',
 '10/14/20',
 '10/15/20',
 '10/16/20',
 '10/17/20',
 '10/18/20',
 '10/19/20',
 '10/20/20',
 '10/21/20',
 '10/22/20',
 '10/23/20',
 '10/24/20',
 '10/25/20',
 '10/26/20',
 '10/27/20',
 '10/28/20',
 '10/29/20',
 '10/30/20',
 '10/31/20',
 '11/1/20',
 '11/2/20',
 '11/3/20',
 '11/4/20',
 '11/5/20',
 '11/6/20',
 '11/7/20',
 '11/8/20',
 '11/9/20',
 '11/10/20',
 '11/11/20',
 '11/12/20',
 '11/13/20',
 '11/14/20',
 '11/15/20',
 '11/16/20',
 '11/17/20',
 '11/18/20',
 '11/19/20',
 '11/20/20',
 '11/21/20',
 '11/22/20',
 '11/23/20',
 '11/24/20',
 '11/25/20',
 '11/26/20',
 '11/27/20',
 '11/28/20',
 '11/29/20',
 '11/30/20',
 '12/1/20',
 '12/2/20',
 '12/3/20',
 '12/4/20',
 '12/5/20',
 '12/6/20',
 '12/7/20',
 '12/8/20',
 '12/9/20',
 '12/10/20',
 '12/11/20',
 '12/12/20',
 '12/13/20',
 '12/14/20',
 '12/15/20',
 '12/16/20',
 '12/17/20',
 '12/18/20',
 '12/19/20',
 '12/20/20',
 '12/21/20',
 '12/22/20',
 '12/23/20',
 '12/24/20',
 '12/25/20',
 '12/26/20',
 '12/27/20',
 '12/28/20',
 '12/29/20',
 '12/30/20',
 '12/31/20',
 '1/1/21',
 '1/2/21',
 '1/3/21',
 '1/4/21',
 '1/5/21',
 '1/6/21',
 '1/7/21',
 '1/8/21',
 '1/9/21',
 '1/10/21',
 '1/11/21',
 '1/12/21',
 '1/13/21',
 '1/14/21',
 '1/15/21',
 '1/16/21',
 '1/17/21',
 '1/18/21',
 '1/19/21',
 '1/20/21',
 '1/21/21',
 '1/22/21',
 '1/23/21',
 '1/24/21',
 '1/25/21',
 '1/26/21',
 '1/27/21',
 '1/28/21',
 '1/29/21',
 '1/30/21',
 '1/31/21',
 '2/1/21',
 '2/2/21',
 '2/3/21',
 '2/4/21',
 '2/5/21',
 '2/6/21',
 '2/7/21',
 '2/8/21',
 '2/9/21',
 '2/10/21',
 '2/11/21',
 '2/12/21',
 '2/13/21',
 '2/14/21',
 '2/15/21',
 '2/16/21',
 '2/17/21',
 '2/18/21',
 '2/19/21',
 '2/20/21',
 '2/21/21',
 '2/22/21',
 '2/23/21',
 '2/24/21',
 '2/25/21',
 '2/26/21',
 '2/27/21',
 '2/28/21',
 '3/1/21',
 '3/2/21',
 '3/3/21',
 '3/4/21',
 '3/5/21',
 '3/6/21',
 '3/7/21',
 '3/8/21',
 '3/9/21']

In [61]:
tweets_and_c19.drop(columns = dates)

tweets_and_c19

,county,original_tweet,tweets_list,tweet_str,tweet_slice,tweet_text,UID,iso2,iso3,code3,...,3/7/21,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21
0,County of San Francisco CA,"['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...",bly disabled enough to get the vaccine (or may...,'if you live in supportive housing you are pro...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
1,County of San Francisco CA,['@robini71 @technolass I have mask fatigue an...,"['If you live in supportive housing, you are p...",['@robini71 @technolass I have mask fatigue an...,ill after all this time hatred and anxiety tra...,'robini technolass i have mask fatigue and sti...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
2,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/qWAQiZsJWX'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
3,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/xHjDwTVEeg'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
4,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/2gYfKCKW3k'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,King County WA,['I never say anything to my cousin anymore bc...,['I never say anything to my cousin anymore bc...,['I never say anything to my cousin anymore bc...,is the only place she hasnâ€™t blocked me and I ...,'i never say anything to my cousin anymore bc ...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
268,King County WA,['@offgridteacher Iâ€™ve eaten indoors but the m...,['I never say anything to my cousin anymore bc...,['@offgridteacher Iâ€™ve eaten indoors but the m...,requirements are pretty strict (masks to enter...,'offgridteacher ive eaten indoors but the mask...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
269,King County WA,"[""@RantsByDesign I'm in mask-free TX, where we...",['I never say anything to my cousin anymore bc...,"[""@RantsByDesign I'm in mask-free TX, where we...",ll have 5k new cases/day.\n\nQuite ok with me ...,rantsbydesign i'm in mask-free tx where we sti...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
270,King County WA,['@ElwynLouis @sounderatheart I still believe ...,['I never say anything to my cousin anymore bc...,['@ElwynLouis @sounderatheart I still believe ...,hould be masked until absolutely everyone is c...,'elwynlouis sounderatheart i still believe we ...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655
271,King County WA,"[""Fox News rouses mask-free Texans at '100% ca...",['I never say anything to my cousin anymore bc...,"[""Fox News rouses mask-free Texans at '100% ca...",ty' diner: 'Think for yourself like Lying Conm...,fox news rouses mask-free texans at ' capacity...,84053033,US,USA,840,...,85015,85282,85417,85596,85824,86002,86234,86234,86540,86655

## Merging New York Times Mask Usage with Twitter/COVID-19 Dataframe

In [62]:
# Reading in the mask usage csv from the New York Times
maskusage = pd.read_csv('mask-use-by-county.csv')

maskusage.head()

   COUNTYFP  NEVER  RARELY  SOMETIMES  FREQUENTLY  ALWAYS
0      1001  0.053   0.074      0.134       0.295   0.444
1      1003  0.083   0.059      0.098       0.323   0.436
2      1005  0.067   0.121      0.120       0.201   0.491
3      1007  0.020   0.034      0.096       0.278   0.572
4      1009  0.053   0.114      0.180       0.194   0.459

In [64]:
# Renaming County Code column to match original dataframe
maskusage_new = maskusage.rename(columns={'COUNTYFP': 'FIPS'})

maskusage_new.head()

   FIPS  NEVER  RARELY  SOMETIMES  FREQUENTLY  ALWAYS
0  1001  0.053   0.074      0.134       0.295   0.444
1  1003  0.083   0.059      0.098       0.323   0.436
2  1005  0.067   0.121      0.120       0.201   0.491
3  1007  0.020   0.034      0.096       0.278   0.572
4  1009  0.053   0.114      0.180       0.194   0.459

In [32]:
# Looking at the dataframe that we will be merging with
tweets_and_c19.head()

,county,original_tweet,tweets_list,tweet_str,tweet_slice,tweet_text,UID,iso2,iso3,code3,...,3/7/21,3/8/21,3/9/21,3/10/21,3/11/21,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21
0,County of San Francisco CA,"['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...",bly disabled enough to get the vaccine (or may...,'if you live in supportive housing you are pro...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
1,County of San Francisco CA,['@robini71 @technolass I have mask fatigue an...,"['If you live in supportive housing, you are p...",['@robini71 @technolass I have mask fatigue an...,ill after all this time hatred and anxiety tra...,'robini technolass i have mask fatigue and sti...,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
2,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/qWAQiZsJWX'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
3,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/xHjDwTVEeg'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820
4,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/2gYfKCKW3k'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34560,34594,34634,34654,34688,34722,34758,34784,34810,34820

In [66]:
# Merging the Mask Usage dataset and Twitter/COVID dataset
usage_tweet_covid = tweets_and_c19.merge(maskusage_new, on='FIPS')

usage_tweet_covid.head()

,county,original_tweet,tweets_list,tweet_str,tweet_slice,tweet_text,UID,iso2,iso3,code3,...,3/12/21,3/13/21,3/14/21,3/15/21,3/16/21,NEVER,RARELY,SOMETIMES,FREQUENTLY,ALWAYS
0,County of San Francisco CA,"['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...","['If you live in supportive housing, you are p...",bly disabled enough to get the vaccine (or may...,'if you live in supportive housing you are pro...,84006075,US,USA,840,...,34722,34758,34784,34810,34820,0.017,0.011,0.035,0.121,0.817
1,County of San Francisco CA,['@robini71 @technolass I have mask fatigue an...,"['If you live in supportive housing, you are p...",['@robini71 @technolass I have mask fatigue an...,ill after all this time hatred and anxiety tra...,'robini technolass i have mask fatigue and sti...,84006075,US,USA,840,...,34722,34758,34784,34810,34820,0.017,0.011,0.035,0.121,0.817
2,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/qWAQiZsJWX'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34722,34758,34784,34810,34820,0.017,0.011,0.035,0.121,0.817
3,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/xHjDwTVEeg'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34722,34758,34784,34810,34820,0.017,0.011,0.035,0.121,0.817
4,County of San Francisco CA,['Why COVID-19 vaccines could make us mask-fre...,"['If you live in supportive housing, you are p...",['Why COVID-19 vaccines could make us mask-fre...,tps://t.co/2gYfKCKW3k'],'why covid- vaccines could make us mask-free,84006075,US,USA,840,...,34722,34758,34784,34810,34820,0.017,0.011,0.035,0.121,0.817